### PR TITLE
First draft of document on the new "measured boot log feature".

### PR DESCRIPTION
**Pull request by maugustosilva**
Signed-off-by: Marcio Silva <marcios@us.ibm.com>

### CODE REVIEW

**Comment by mpeters** [comment]
This is a good start. Although more example policies would definitely be needed.

**Comment by aplanas** [comment]
Seems that there are missing bits here:

* The format of the mb_refstate is not explained
* There is not example about how to create a minimal viable policy
* There is no indication about how this policy can be loaded (via the measured_boot_imports parameter in cloud_verifier section)

**Comment by THS-on** [comment]
@maugustosilva now that the Example policy exists should  we just reference that in the documentation for now and merge this PR as initial documentation of that feature?

**Comment by mpeters** [comment]
I agree, this is now more complete with the other example, so I'm ready to merge if @maugustosilva is.

**Pull request merged**
